# Generated by Django 3.1.1 on 2020-09-22 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_auto_20200920_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finished_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
