# Generated by Django 3.1.1 on 2020-09-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_auto_20200922_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
