# Generated by Django 3.1.1 on 2020-09-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_todo_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='islem_aciklama',
            field=models.SlugField(max_length=255),
        ),
    ]
